[tool.poetry]
name = "mapped.pb"
version = "0.1.0"
description = "public Mapped Platform Service Definitions using protobuf"
authors = ["Mapped <support@mapped.com>"]
license = "Apache-2.0"
homepage = "https://www.mapped.com"
repository = "https://github.com/mapped/pb"
keywords = ["mapped", "protobuf"]
readme = "README.md"
packages = [
    {include = "mapped_pb", from = "./", format = "sdist"},
    ]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
protobuf = "^4.21.7"
betterproto = {version = "^2.0.0b6", allow-prereleases = true}

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

